apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: plane-secret-store
  namespace: 
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: plane-secret-service-account