apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plane-external-secret
  namespace: 
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: plane-secret-store
    kind: SecretStore
  target:
    name: plane-secret
    creationPolicy: Owner
  data:
  - secretKey: plane-db-username
    remoteRef:
      key: #AWS Secrets Manager secret name
      property: username #AWS Secrets Manager secret key
